/**
 * Authentication.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './user-dto';


export interface AuthResponse { 
    token?: string;
    refreshToken?: string;
    expiresAt?: string;
    user?: UserDto;
}

