/**
 * Authentication.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProblemDetailsStatusDto } from './problem-details-status';


export interface ProblemDetailsDto { 
    type?: string | null;
    title?: string | null;
    status?: ProblemDetailsStatusDto | null;
    detail?: string | null;
    instance?: string | null;
}

