/**
 * Authentication.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleDtoDto } from './role-dto';


export interface UserDtoDto { 
    id?: string;
    email?: string;
    firstName?: string | null;
    lastName?: string | null;
    role?: RoleDtoDto;
}

