// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiteManagement.API.DAL;

#nullable disable

namespace SiteManagement.API.Migrations
{
    [DbContext(typeof(SiteManagementDbContext))]
    [Migration("20260204193051_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SiteManagement.API.DAL.Entities.PlannedDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NumberOfTimeSplots")
                        .HasColumnType("int");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.HasIndex("ScheduleId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("PlannedDays");
                });

            modelBuilder.Entity("SiteManagement.API.DAL.Entities.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClosedDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("SiteManagement.API.DAL.Entities.TimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsBooked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PlannedDayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimeSlotNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlannedDayId", "TimeSlotNumber")
                        .IsUnique();

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("SiteManagement.API.DAL.Entities.PlannedDay", b =>
                {
                    b.HasOne("SiteManagement.API.DAL.Entities.Site", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteManagement.API.DAL.Entities.Site", null)
                        .WithMany("Schedule")
                        .HasForeignKey("SiteId");
                });

            modelBuilder.Entity("SiteManagement.API.DAL.Entities.TimeSlot", b =>
                {
                    b.HasOne("SiteManagement.API.DAL.Entities.PlannedDay", null)
                        .WithMany()
                        .HasForeignKey("PlannedDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiteManagement.API.DAL.Entities.Site", b =>
                {
                    b.Navigation("Schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
