/**
 * SiteManagement.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const BookState = {
    BookInProgress: 'BookInProgress',
    Booked: 'Booked',
    Paid: 'Paid',
    Plaid: 'Plaid'
} as const;
export type BookState = typeof BookState[keyof typeof BookState];

