/**
 * SiteManagement.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookState } from './book-state';


export interface BookTimeSlotRequest { 
    plannedDayId: string;
    courtId: string;
    timeSlotNumber: number;
    weekNumber: number;
    bookState: BookState;
}
export namespace BookTimeSlotRequest {
}


