/**
 * SiteManagement.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const Comparison = {
    Equal: 'Equal',
    LessThan: 'LessThan',
    LessThanOrEqual: 'LessThanOrEqual',
    GreaterThan: 'GreaterThan',
    GreaterThanOrEqual: 'GreaterThanOrEqual',
    NotEqual: 'NotEqual',
    Contains: 'Contains',
    StartsWith: 'StartsWith',
    EndsWith: 'EndsWith'
} as const;
export type Comparison = typeof Comparison[keyof typeof Comparison];

