/**
 * SiteManagement.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiSitesPageGetPageNumberParameter } from './api-sites-page-get-page-number-parameter';


export interface CreateCourtRequest { 
    number: ApiSitesPageGetPageNumberParameter;
}

