/**
 * SiteManagement.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DayOfWeek } from './day-of-week';


export interface CreatePlannedDayRequest { 
    dayOfWeek: DayOfWeek;
    numberOfTimeSlots: number;
    startTime: string | null;
}



