/**
 * SiteManagement.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookTimeSlotRequestTimeSlotNumber } from './book-time-slot-request-time-slot-number';


export interface CreatePlannedDayRequest { 
    dayOfWeek: number;
    numberOfTimeSlots: BookTimeSlotRequestTimeSlotNumber;
}

