/**
 * SiteManagement.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Comparison } from './comparison';
import { FilterAssociation } from './filter-association';


export interface ExpressionFilter { 
    propertyName?: string | null;
    valueString?: string | null;
    comparison?: Comparison;
    filterAssociation?: FilterAssociation;
}
export namespace ExpressionFilter {
}


