/**
 * SiteManagement.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpressionFilter } from './expression-filter';
import { FilterAssociation } from './filter-association';


export interface FilterGroup { 
    filters?: Array<ExpressionFilter>;
    filterAssociation?: FilterAssociation;
}



