/**
 * SiteManagement.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortDescriptor } from './sort-descriptor';
import { FilterGroup } from './filter-group';


export interface PageRequest { 
    pageNumber?: number;
    pageSize?: number;
    filters?: Array<FilterGroup> | null;
    sorts?: Array<SortDescriptor> | null;
}

