/**
 * SiteManagement.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiSitesPageGetPageNumberParameter } from './api-sites-page-get-page-number-parameter';
import { TimeSlotResponse } from './time-slot-response';


export interface PlannedDayResponse { 
    id: string;
    dayOfWeek: number;
    numberOfTimeSlots: ApiSitesPageGetPageNumberParameter;
    timeSlots: Array<TimeSlotResponse>;
}

