/**
 * SiteManagement.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DayOfWeek } from './day-of-week';
import { TimeSlotResponse } from './time-slot-response';


export interface PlannedDayResponse { 
    id: string;
    dayOfWeek: DayOfWeek;
    numberOfTimeSlots: number;
    timeSlots: Array<TimeSlotResponse>;
}
export namespace PlannedDayResponse {
}


