/**
 * SiteManagement.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CourtResponse } from './court-response';
import { PlannedDayResponse } from './planned-day-response';


export interface SiteDetailsResponse { 
    id: string;
    name: string;
    revenue: number;
    closedDays: Array<string>;
    courts: Array<CourtResponse>;
    schedule: Array<PlannedDayResponse>;
}

