/**
 * SiteManagement.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookState } from './book-state';


export interface TimeSlotResponse { 
    id: string;
    timeSlotNumber: number;
    courtId: string;
    weekNumber: number;
    bookState: BookState;
    dateTime: string;
}



