#!/bin/sh
# ref: https://help.github.com/articles/adding-an-existing-project-to-github-using-the-command-line/
#
# Usage example: /bin/sh ./git_push.sh wing328 openapi-petstore-perl "minor update" "gitlab.com"

git_user_id=$1
git_repo_id=$2
release_note=$3
git_host=$4

if [ "$git_host" = "" ]; then
    git_host="github.com"
    echo "[INFO] No command line input provided. Set \$git_host to $git_host"
fi

if [ "$git_user_id" = "" ]; then
    git_user_id="GIT_USER_ID"
    echo "[INFO] No command line input provided. Set \$git_user_id to $git_user_id"
fi

if [ "$git_repo_id" = "" ]; then
    git_repo_id="GIT_REPO_ID"
    echo "[INFO] No command line input provided. Set \$git_repo_id to $git_repo_id"
fi

if [ "$release_note" = "" ]; then
    release_note="Minor update"
    echo "[INFO] No command line input provided. Set \$release_note to $release_note"
fi

# NOTE:
# This script is generated by OpenAPI Generator and is intended for publishing a
# generated client as a standalone package to a separate Git repository.
# In this project the generated client lives inside an existing repository, so
# running git commands from here would be confusing and potentially harmful.
#
# To avoid accidental use, all git operations have been intentionally disabled.
# Use your normal project git workflow instead of this script.

echo "[INFO] git_push.sh is disabled in this project."
echo "[INFO] No git operations were performed."
echo "[INFO] Please use your standard git workflow (git add/commit/push) instead."

# Exit with a non-zero status to make it clear this script is not meant to be used.
exit 1

# The original implementation (git init/add/commit/remote/push) has been removed
# to prevent accidental misuse. If you explicitly need such functionality, create
# a dedicated, reviewed script for your workflow instead.

# (Intentionally left without git commands)
